---
include:
  - project: shore/ci-stuff
    file: templates/pre-commit.yml

pre-commit-try-repo:
  stage: test
  image: registry.shore.co.il/ci-images:pre-commit
  tags: [ns4.shore.co.il]
  variables:
    PIP_CONSTRAINT: /tmp/constraint.txt
    TF_CLI: tofu
    XDG_CACHE_HOME: "$CI_PROJECT_DIR/.cache"
  before_script:
    - apt-get update
    - apt-get install -y packer=1.9.5-1 tofu
    # See https://github.com/yaml/pyyaml/issues/736 for the reason for this
    # workaround. Needed until Ansible doesn't require pyyaml<6.
    - echo 'Cython < 3.0' > "$PIP_CONSTRAINT"
  script:
    - pre-commit try-repo --all-files ./
  cache:
    paths:
      - .cache/
